---
# -------------------------------------------
# cluster-admin already exists
# -------------------------------------------
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  creationTimestamp: null
#  name: cluster-admin
#  annotations:
#    rbac.authorization.kubernetes.io/autoupdate: "true"
#rules:
#- apiGroups:
#  - '*'
#  resources:
#  - '*'
#  verbs:
#  - '*'
#- nonResourceURLs:
#  - '*'
#  verbs:
#  - '*'
#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system